# .github/workflows/deploy.yml
name: Build and deploy (Vite React) to Azure Web App - avocarbon-action-plan

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'
      
      - name: Create .env file
        run: |
          echo "VITE_API_URL=${{ secrets.VITE_API_URL }}" > .env

      - name: Check env file
        run: |
          cat .env

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_5EC30B55B5BA4773AA48AA423CD7C87F }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_5F86CA484C0E49E7BB9D0F8BE156C289 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_F6D385931F77442A83287E6F84995184 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: avocarbon-action-plan
          slot-name: Production
          package: dist
